{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lineage-ota-server.fullname" . }}
  labels:
    {{- include "lineage-ota-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $existing := lookup "v1" "Secret" .Release.Namespace (include "lineage-ota-server.fullname" .) }}
  {{- if .Values.uploadToken }}
  upload-token: {{ .Values.uploadToken | b64enc }}
  {{- else if $existing }}
  upload-token: {{ index $existing.data "upload-token" }}
  {{- else }}
  upload-token: {{ randAlphaNum 40 | b64enc }}
  {{- end }}
{{- end }}
